# permissions for end users to edit secretmirrors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretmirror-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: secret-mirror-operator
    app.kubernetes.io/part-of: secret-mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretmirror-editor-role
rules:
- apiGroups:
  - secret.nakamasato.com
  resources:
  - secretmirrors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.nakamasato.com
  resources:
  - secretmirrors/status
  verbs:
  - get
