apiVersion: secret.nakamasato.com/v1alpha1
kind: SecretMirror
metadata:
  labels:
    app.kubernetes.io/name: secretmirror
    app.kubernetes.io/instance: secretmirror-sample
    app.kubernetes.io/part-of: secret-mirror-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secret-mirror-operator
  name: secret
  namespace: dst
spec:
  fromNamespace: src
