name: test

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.*'
      - .github/workflows/test.yml
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - uses: actions/checkout@master

      - run: |
          make test
